name       : gnome-sudoku
version    : '43.0'
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-sudoku/43/gnome-sudoku-43.0.tar.xz : 7ed274289cf5ca410b1c92b1537050a5c362f7db3399a32b5343d0de70466e49
homepage   : https://wiki.gnome.org/Apps/Sudoku/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
