name       : gnome-sudoku
version    : 3.24.0
release    : 3
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-sudoku/3.24/gnome-sudoku-3.24.0.tar.xz : 04a29447889448ee5d5840cb5b2fd05ce6031c38a24809ce4919647ee6f485d7
license    : GPL-3.0
component  : games.puzzle
summary    : Sudoku is a Japanese logic game that exploded in popularity in 2005
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
