name       : gnome-sudoku
version    : '44.0'
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-sudoku/44/gnome-sudoku-44.0.tar.xz : 6518d9233a46d7e13805ac787667ba4701948d9ed41a47b88797fcdba43b8fba
homepage   : https://wiki.gnome.org/Apps/Sudoku/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
