name       : gnome-sudoku
version    : 3.20.5
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-sudoku/3.20/gnome-sudoku-3.20.5.tar.xz : 339480745513692e782eaf4312326f2aecca7acd822e3eaebc678332cb5ecb98
license    : GPL-3.0
component  : games.puzzle
summary    : Sudoku is a Japanese logic game that exploded in popularity in 2005
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
