name       : gnome-sudoku
version    : '40.2'
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-sudoku/40/gnome-sudoku-40.2.tar.xz : 36120531e3c7139581ea3800fbfe3c2b31694c440145ecc897ac34e562d754a3
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku is a Japanese logic game that exploded in popularity in 2005
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
