name       : gnome-sudoku
version    : '42.0'
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-sudoku/42/gnome-sudoku-42.0.tar.xz : 1d2eb4ddb8026b443645cf3585b8df1244e3828ee1c07518052b2599e1c5c28f
homepage   : https://wiki.gnome.org/Apps/Sudoku/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
