name       : gnome-sudoku
version    : 3.22.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-sudoku/3.22/gnome-sudoku-3.22.2.tar.xz : 08c48ba0ce3497727e5e19b086d28258e4bab61834c2f7e23fce256685a5e2eb
license    : GPL-3.0
component  : games.puzzle
summary    : Sudoku is a Japanese logic game that exploded in popularity in 2005
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
